#!/usr/bin/env sh

# Set up Rails app. Run this script immediately after cloning the codebase.
# https://github.com/thoughtbot/guides/tree/master/protocol

bundle install --binstubs=bin/stubs
bundle exec rake db:setup
touch .env

if [ ! -f .env ]; then
  echo "RACK_ENV=development" >> .env
fi
